var mongoose = require('mongoose')
require('./user')
exports.User = mongoose.model('user')
require('./question')
exports.Question = mongoose.model('question')
require('./answer')
exports.Answer = mongoose.model('answer')