var mongoose = require('mongoose')
require('./user')
exports.User = mongoose.model('User')
require('./question')
exports.Question = mongoose.model('Question')
require('./answer')
exports.Answer = mongoose.model('Answer')